#:kivy 1.9

<BtmsValidRoot>:
	orientation: 'vertical'
	canvas.before:
        Color:
            rgb: .6, .6, .6
        Rectangle:
            size: self.size
            source: 'images/background.png'
    event_btn: event_btn.__self__
    event_title: event_title.__self__
    event_date_btn: event_date_btn.__self__
    event_date: event_date.__self__

	ScreenManager:
		id: sm
		
		Screen:
			name: 'server_connect'
			AnchorLayout:
				anchor_x: "center"
				anchor_y: "center"
			
                BoxLayout:
                    id: kv_login_list

                    size_hint_x: .8
                    size_hint_y: .8
                    orientation: 'vertical'
                    spacing: 10

                    TextInput:
                        id: kv_server_adress
                        text: "192.168.178.36:8080"
                        hint_text: "Server Adress: z.B. 192.168.178.1"
                        multiline: False
                        font_size: "30dp"
                        on_text_validate: root.start_wamp_component(kv_server_adress.text)
                    #TextInput:
                    #    id: kv_user_log
                    #    size_hint_y: .5
                    #    size_hint_x: 1
                    #    hint_text: "log..."
                    #    multiline: True
                    #    font_size: "12dp"

                    BoxLayout:
                        id: kv_user_select

                        TextInput:
                            id: kv_user_input
                            size_hint_y: 1
                            size_hint_x: .7
                            text: "jaques"
                            hint_text: "Username"
                            multiline: False
                            font_size: "30dp"

                            on_text_validate: root.start_wamp_component_auth(kv_server_adress.text, kv_user_input.text, kv_password_input.text)
                        Button:
                            id: kv_user_change
                            text: 'change'
                            size_hint_y: 1
                            size_hint_x: .3
                            font_size: "15dp"
                            on_release: sm.current = 'login_user'

                    TextInput:
                        id: kv_password_input
                        size_hint_y: 1
                        text:
                        password: True
                        multiline: False
                        font_size: "50dp"

                        on_text_validate: root.start_wamp_component_auth(kv_server_adress.text, kv_user_input.text, kv_password_input.text)


                    GridLayout:
                        cols: 3
                        size_hint_y: 3

                        Button:
                            text: "7"
                            font_size: "30dp"
                            pos_hint: {'x': .7, 'y': .53}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "7";

                        Button:
                            text: "8"
                            font_size: "30dp"
                            pos_hint: {'x': .8, 'y': .53}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "8";

                        Button:
                            text: "9"
                            font_size: "30dp"
                            pos_hint: {'x': .9, 'y': .53}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "9";

                        Button:
                            text: "4"
                            font_size: "30dp"
                            pos_hint: {'x': .7, 'y': .43}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "4";

                        Button:
                            text: "5"
                            font_size: "30dp"
                            pos_hint: {'x': .8, 'y': .43}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "5";

                        Button:
                            text: "6"
                            font_size: "30dp"
                            pos_hint: {'x': .9, 'y': .43}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "6";


                        Button:
                            text: "1"
                            font_size: "30dp"
                            pos_hint: {'x': .7, 'y': .33}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "1";

                        Button:
                            text: "2"
                            font_size: "30dp"
                            pos_hint: {'x': .8, 'y': .33}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "2";

                        Button:
                            text: "3"
                            font_size: "30dp"
                            pos_hint: {'x': .9, 'y': .33}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "3";


                        Button:
                            text: "0"
                            font_size: "30dp"
                            pos_hint: {'x': .7, 'y': .23}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += "0";

                        Button:
                            text: "."
                            font_size: "30dp"
                            pos_hint: {'x': .8, 'y': .23}
                            size_hint: .1, .1
                            on_release: kv_password_input.text += ".";

                        Button:
                            text: "CL"
                            font_size: "30dp"
                            pos_hint: {'x': .9, 'y': .23}
                            size_hint: .1, .1
                            on_release: kv_password_input.text = "";


                    Button:
                        id: kv_login_button
                        size_hint_y: 1
                        text: 'login'
                        on_release: root.start_wamp_component_auth(kv_server_adress.text, kv_user_input.text, kv_password_input.text)
	
		Screen:
			name: 'login_user'
			#FloatLayout:
             #   size_hint: 1, 1
              #  pos_hint: {'x': 0, 'y': 0}
               # ScrollView:
                #    size_hint: 1, 1
                #TODO not working on android phone
            GridLayout:
                id: kv_user_list
                size_hint: 1, 1
                cols: 2
                #row_default_height: '40dp'
                padding: 0
                spacing: '5dp'

						
				
							
							
		Screen:
			name: 'login_auth'
			AnchorLayout:
				anchor_x: "center"
				anchor_y: "center"
				
					

						
		Screen:
			name: 'work1'
			id: detector

            Button:
				id: event_btn
				pos_hint: {'x': 0, 'y': .9}
				size_hint: .35, .1
				text: 'select...'
				on_release: event_title.open(self)
				size_hint_y: None
				height: event_time.height
				background_normal: 'atlas://data/images/defaulttheme/spinner'
				background_down: 'atlas://data/images/defaulttheme/spinner_pressed'
				background_disabled_normal: 'atlas://data/images/defaulttheme/spinner_disabled'

			DropDown:
				id: event_title
				font_size: self.height * .35
				on_select: event_btn.text = '{}'.format(args[1])
                on_parent: self.dismiss()


			Button:
				id: event_date_btn
				pos_hint: {'x': .35, 'y': .9}
				font_size: self.height * .3
				size_hint: .35, .1
				text: 'select...'
				on_release: event_date.open(self)
				size_hint_y: None
				height: event_time.height
				background_normal: 'atlas://data/images/defaulttheme/spinner'
				background_down: 'atlas://data/images/defaulttheme/spinner_pressed'
				background_disabled_normal: 'atlas://data/images/defaulttheme/spinner_disabled'


			DropDown:
				id: event_date
				font_size: self.height * .35
				on_parent: self.dismiss()
				on_select: event_date_btn.text = '{}'.format(args[1])


			Spinner:
				id: event_time
				text: 'loading...'
				pos_hint: {'x': .7, 'y': .9}
				size_hint: .3, .1
				font_size: self.height * 0.35
				#on_text: number_display_box.text = self.text;
				on_text: root.set_event_time(self.text)
			
            Button:
                pos_hint: {'x': 0, 'y': .375}
                size_hint: 1, .5
                id: result_screen
                text: ''

            Button:
                pos_hint: {'x': 0, 'y': .25}
                size_hint: 1, .1
                id: result_label
                #font_size: self.height * .25
                text: ''


            Button:
                pos_hint: {'x': .0, 'y': .125}
                size_hint: 1, .1
                id: test
                #text: 'test'
                text: '\\n'.join(map(repr, root.symbols))
                on_release: root.refresh_report()



            BoxLayout:
                size_hint_y: None
                pos_hint: {'x': .0, 'y': .0}
                size_hint: 1, .1

                #Button:
                    #text: 'Scan'
                    #on_release: root.start()

                #Button:
                    #text: 'Stop'
                    #on_release: root.stop()
                #ToggleButton:
                    #id: lamp_btn
                    #text: 'Lamp'
                    #on_release: root.toggle_lamp()

                ToggleButton:
                    id: kv_check_in_out
                    text: 'Check In'
                    background_color: [0,1,0,1]
                    on_release: root.check_in_out()

                Button:
                    id: kv_show_log
                    text: 'Log'
                    on_release: root.get_journal('valid_today','0')
                Button:
                    id: kv_user_button
                    text: "User"
                    on_release: root.logout(1)
                Button:
                    id: kv_settings_button
                    text: "Connect"
                    on_release: root.get_settings()

        Screen:
			name: 'log'
			ScrollView:
				size_hint: 1, .9
				pos_hint: {'x': 0, 'y': .1}
				scroll_timeout: 100
				scroll_distance: 20


				GridLayout:
					id: journal_list_box
					pos_hint: {'x': 0, 'y': 0.0}
					size_hint: 1, None
					padding: 0
					spacing: 1
					#height: 30
					cols: 5
					rows: None
					do_scroll_x: False
					row_default_height: 45

			Button:
                pos_hint: {'x': .0, 'y': .0}
                size_hint: .8, .1
                id: kv_back
                text: 'Back'
                on_release: sm.current = "work1"
			Button:
                pos_hint: {'x': .8, 'y': .0}
                size_hint: .1, .1
                id: kv_back
                text: 'All'
                on_release: root.get_journal('valid_today','0')
            Button:
                pos_hint: {'x': .9, 'y': .0}
                size_hint: .1, .1
                id: kv_result_indicator
                text: ''
                on_release: sm.current = "work1"

        Screen:
			name: 'settings'
			ScrollView:
				size_hint: 1, .9
				pos_hint: {'x': 0, 'y': .1}
				scroll_timeout: 100
				scroll_distance: 20


				GridLayout:
					id: settings_list_box
					pos_hint: {'x': 0, 'y': 0.0}
					size_hint: 1, None
					padding: 0
					spacing: 1
					#height: 30
					cols: 1
					rows: None
					do_scroll_x: False
					row_default_height: 45

			Button:
                pos_hint: {'x': .0, 'y': .0}
                size_hint: 1, .1
                id: kv_back
                text: 'Back'
                on_release: sm.current = "work1"